"""
Exceptions for the Radoff API.

Pure move from the former `api.py` (see S-06b): same names, same base
class, same docstrings. Extracted first because nothing else in the `api`
package depends on anything but this module.

Card M-02 adds the arch 2.0 error taxonomy: one class per HTTP semantic
`_check_response_status` (see `api/client.py`) can now tell apart, instead
of the single `APIAuthError` every non-200 used to collapse into (finding
F3). They all derive from `APIAuthError` **on purpose**, even the ones that
have nothing to do with authentication: that name is this client's
historical catch-all for "the HTTP call did not return 200", and two
existing contracts key off it - `_ISOLATABLE_DEVICE_ERRORS`
(`api/client.py`, card S-13: which per-device failures may be isolated
instead of failing the whole poll) and `coordinator.py`'s `except
APIAuthError` clause. Subclassing keeps both working untouched while
letting every caller discriminate; renaming `APIAuthError` itself into
something honest (`APIResponseError`) would touch both and is not this
card's job.
"""


class APIAuthError(Exception):
    """Exception class for auth error."""


class APIConnectionError(Exception):
    """Exception class for connection error."""


class DomainNotFoundError(Exception):
    """Exception class for domain not found error."""


class BearerTokenNotFoundError(Exception):
    """Exception class for bearer token not found/available."""


class APIDomainAccessError(APIAuthError):
    """
    HTTP 403 in arch 2.0: the account does not belong to the queried domain.

    Card M-02. The 403 has one precise cause in arch 2.0 (T-02 D-29, and
    reproduced for real in M-01 - see
    `tests/fixtures/dev/error__devices_foreign_domain.json`): the request
    carried a `domain_prefix` the caller has no access to, its body being
    `{"error": "Forbidden: you do not belong to domain '<prefix>'"}`.

    It is therefore **not** retryable and **not** an authentication problem:
    the credentials are fine and a new token would change nothing - the
    stored domain is what is wrong, so the fix is a reconfiguration.
    `coordinator.py` turns it into a `ConfigEntryError` (never
    `ConfigEntryAuthFailed`: re-asking for the password would be a dead end)
    and `API.get_devices()` never isolates it per device, since every device
    of that domain fails identically.

    A behaviour change worth remembering: in arch 1.x this same situation
    came back as a 401 and was indistinguishable from an expired session.
    """


class APIRateLimitError(APIAuthError):
    """
    HTTP 429: the shared API Gateway quota for this stage was exceeded.

    Card M-02, T-02 D-21/D-22. Generated by API Gateway rather than by the
    application, with the body `{"message": "Too Many Requests"}` and **no**
    `Retry-After` header, so `retry_after` carries the delay *we* computed
    (exponential from `RATE_LIMIT_BACKOFF_START`, with jitter, capped at
    `RATE_LIMIT_BACKOFF_MAX` - see const.py and
    `API._rate_limit_backoff`), not one the backend asked for.

    The quota is per stage and shared with the Radoff mobile and web apps:
    hitting it says nothing about this installation's own politeness, and
    nothing at all about the devices, which is why the intended reaction is
    "skip this cycle" rather than "retry now" - an immediate retry is what
    makes a saturated stage worse.
    """

    def __init__(self, message: str, retry_after: float) -> None:
        """Store the backoff delay, in seconds, this 429 should be honoured with."""
        super().__init__(message)
        self.retry_after = retry_after


class APIServerError(APIAuthError):
    """
    HTTP 5xx: a transient failure on the Radoff side. Retryable as-is.

    Card M-02. Worth being explicit about what does *not* reach here: T-02
    D-29 established that failures of the soft dependencies (DynamoDB,
    Aurora) do not produce a 5xx at all - they produce `null` fields in an
    otherwise-200 response. A real 5xx is therefore the API Gateway or the
    application itself being unavailable, which is exactly the case the
    `Retry` in `API._create_session` still retries automatically before this
    ever gets raised.
    """


class APIDeviceNotFoundError(APIAuthError):
    """
    HTTP 404 on a single device: unknown serial, or a device with no data.

    Card M-02. Reproduced in M-01 (see
    `tests/fixtures/dev/error__device_detail_unknown_serial.json`, body
    `{"error": "Device '<serial>' not found"}`). It is scoped to one device
    and says nothing about the session or the domain, so it stays isolatable
    per device (card S-13): the other devices of the same poll keep
    updating.
    """


class APIUnknownDeviceTypeError(APIAuthError):
    """
    HTTP 404 from `/analytics/measures-ranges`: unknown `device_type`.

    Card M-02. A different shape of 404 from the one above, and the reason
    the body has to be inspected rather than the path (T-02 D-29: the error
    body in arch 2.0 is not uniform - M-01 alone captured three shapes).
    This one carries the list of registered device types in `available`
    (see `tests/fixtures/dev/error__measures_ranges_unknown_type.json`),
    which is genuinely useful diagnostics: it names exactly what the
    backend's catalogue holds at that moment, so `available` is kept on the
    exception instead of being flattened into the message.

    Nothing calls `/analytics/measures-ranges` yet - the schema-driven
    client is card M-04 - but the semantic belongs to the taxonomy this card
    puts in place, and the fixture to test it against already exists.
    """

    def __init__(self, message: str, available: list[str]) -> None:
        """Store the `available` device types the backend listed in the 404 body."""
        super().__init__(message)
        self.available = available
